# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  minicarsales:
    image: minicarsales
    build:
      context: .
      dockerfile: MiniCarsales.API/Dockerfile
    ports:
      - 80